name: Deploy to Cloud Run

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug check secret
      run: |
        echo "Secret length: ${#GCP_SA_KEY}"
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
    
    - name: push to cloud run        
      run: |
        echo "DATABASE_URL: ${{ secrets.GCP_SA_KEY }}"
        docker build -t gcr.io/xz-share/my-course-platform:latest --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -f Dockerfile . --platform linux/amd64
        gcloud auth configure-docker --quiet
        docker push gcr.io/xz-share/my-course-platform:latest

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy my-course-platform \
    #       --project=xz-share \
    #       --region=australia-southeast1 \
    #       --image gcr.io/xz-share/my-course-platform:latest \
    #       --platform=managed \
    #       --allow-unauthenticated
