name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug check secret
      run: |
        echo "Secret length: ${#GCP_SA_KEY}"
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-course-playform \
          --project=xz-share \
          --region=australia-southeast1-a \
          --source=. \
          --platform=managed \
          --allow-unauthenticated
